### PR TITLE
Add a Charset option

### PR DESCRIPTION
**Pull request by kellpossible**
I've also made it set CHARSET to UTF-8 by default, this might be a breaking change for some people? Happy to change it back to CHARSET by default and make people find this option instead if that's better.

### CODE REVIEW

**Comment by ogoffart** [comment]
Thanks for the patch!
I published the version 0.1.4

**Comment by ogoffart** [comment]
Actually, thinking about it a bit more, Why do you need this option for? Do you really need anything else than UTF-8.
The reason i'm asking is because I realized that i've been trying to keep the arguments the same as xgettext, to use it as a drop-in replacement. But `-c` is already taken for something else.
I am wondering if I should not remove the `-c` and just keep `--comment`

**Comment by kellpossible** [comment]
Oops, sorry I didn't spot the -c taken for something else, maybe just keep the charset. Is it possible to use strings/source files with a different encoding than utf-8 in Rust? At my previous work we were working a lot with windows-1252.

**Comment by ogoffart** [comment]
Btw, i removed the `-c`  in 0.1.5  (bur the --charset is still there)

(I know it is technically a breaking change. But I doubt anyone was relying on the -c already. And anyway, it is still a 0.x)

**Comment by kellpossible** [comment]
thanks for the heads up! that sounds reasonable

**Pull request merged**
